[server]
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 500
enableWebsocketCompression = false
maxMessageSize = 500  # <--- NEW: Increases the internal buffer

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
